---
- name: Uncomment the net.ipv4.ip_forward line if it exists
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward=1'
    state: present

- name: Ensure net.ipv4.ip_forward is set to 1
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward=1'
    state: present

- name: Add MASQUERADE rule to iptables
  iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE
    source: "{{ private_cidr_block }}"
    out_interface: "{{ primary_interface }}"
    state: present

- name: Allow established connections to be forwarded
  iptables:
    chain: FORWARD
    jump: ACCEPT
    match: state
    ctstate: RELATED,ESTABLISHED
    state: present

- name: Allow forwarding from the private subnet
  iptables:
    chain: FORWARD
    jump: ACCEPT
    source: "{{ private_cidr_block }}"
    state: present

- name: Apply changes
  command: sysctl -p 